version: 0.0
os: linux
file_exists_behavior: OVERWRITE
files:
  - source: backend-postgresql
    destination: /var/www/3tier-app/backend-postgresql

hooks:
  BeforeInstall:
    - location: backend-postgresql/scripts/codedeploy-before-install.sh
      timeout: 1800
      runas: root

  AfterInstall:
    - location: backend-postgresql/scripts/codedeploy-deploy-backend.sh
      timeout: 1800
      runas: root

  ApplicationStart:
    - location: backend-postgresql/scripts/codedeploy-application-start.sh
      timeout: 1800
      runas: root
